# Database configuration
# ---- QA ----
db.jdbc.url=jdbc:oracle:thin:@//10.0.0.38:1521/dhaprcp1
# ---- PROD ----
#db.jdbc.url=jdbc:oracle:thin:@//10.1.0.78:1521/dhaordb
# ---- Test ----
#db.jdbc.url=jdbc:oracle:thin:@//10.0.0.75:1521/dhatst2

db.username=dbuser
db.password=1r3teecee

# BAS directory locations (all relative to the working directory, i.e. -Ddir.work specified as command-line argument
dir.out=Services/DHA/BAS/Out
dir.sent=Services/DHA/BAS/Sent
dir.processed=Services/DHA/BAS/Processed
dir.reported=Services/DHA/BAS/Reported

# Properties for BUILD task
build.last.year.end=2012-11-01

# Properties for UPLOAD task
upload.batch.size=50
upload.sleep.minutes=1

# Properties for REPORT task
report.expiry.days=2

# TREASURY FTP configuration
ftp.host=10.0.0.7
ftp.port=21
ftp.username=DHA
ftp.password=IR3_FTP_2011
ftp.inbox=/DHA/inbox
ftp.outbox=/DHA/outbox

# BAS e-mail notification configuration
mail.smtp.host=10.0.0.5
mail.smtp.port=25
mail.from=dha-bas@interfile.co.za
mail.reply.to=opshelpdesk@interfile.co.za
mail.treasury=BASOPS@Treasury.gov.za
mail.home.affairs=Daphney.Maleka@dha.gov.za
mail.interfile=DHASupport@interfile.co.za
