#################################################
# FACILITY PROPERTIES FILE
# THIS FILE LINKS THE PKFACILITYID TO THE STRING
# SEQUENCE THAT REPRESENTS THAT FACILITY
#################################################
# RANDBURG DISTRCT OFFICE
39=RND
# HARRISON STREET REGIONAL OFFICE
20045=HAR
# ACACIA DISTRICT OFFICE
100149=ACA
# KRUGERSDORP DISTRICT OFFICE
100177=KRU
# ALEXANDRA DISTRICT OFFICE
100211=ALX
# PRETORIA REGIONAL OFFICE
100268=PTA
# EDENVALE DISTRICT OFFICE
100346=END
# GERMISTON REGIONAL OFFICE
100357=GER
# AMAJUBA DISTRICT OFFICE
103591=AMA
# COMMERCIAL ROAD DISTRICT OFFICE
103598=COM
# ETHEKWINI REGIONAL OFFICE
103606=ETH
# KWADUKUZA DISTRICT OFFICE
103615=KWD
# PINETOWN DISTRICT OFFICE
103622=PIN
# UMGUNGUNDLOVU DISTRICT OFFICE
103630=UMG
# UGU DISTRICT OFFICE
104749=UGU
# PROSPECTON DISTRICT OFFICE
111345=PRO
# UTHUNGULU DISTRICT OFFICE
111353=UTG
# SCOTTSBURGH DISTRICT OFFICE
111362=SCT
# TONGAAT DISTRICT OFFICE
111371=TGT
# EMPANGENI DISTRICT OFFICE
111378=EMP
#LADYSMITH DISTRICT OFFICE
116411=LDS
#KOKSTAD DISTRICT OFFICE
116958=KST
#KHAYELITSHA REGIONAL OFFICE
127539=KHY
#MALMESBURY DISTRICT OFFICE
127931=MAL
#GEORGE REGIONAL OFFICE
128141=GRG
#BELVILLE DISTRICT OFFICE
128385=BEL
#PAARL REGIONAL OFFICE
128702=PRL
#MITCHELLS PLAIN DISTRICT OFFICE
129138=MPN
#CAPE TOWN REGIONAL OFFICE
131661=CTN
#WYNBERG DISTRICT OFFICE
132623=WYN
#WORCESTER DISTRICT OFFICE
132815=WOR
#CALEDON DISTRICT OFFICE
133607=CAL
#HAZYVIEW DISTRICT OFFICE
169808=HAZ
#WITBANK DISTRICT OFFICE
169914=WTB
#NELSPRUIT REGIONAL OFFICE
183705=NEL
#ERMELO REGIONAL OFFICE
183985=ERM
#PIET RETIEF DISTRICT OFFICE
184470=PTR
#BETHAL DISTRICT OFFICE
184652=BTL
#KOMATIPOORT DISTRICT OFFICE
184842=KMP
#LEBOMBO  BORDER POST
187840=LBB
#KIMBERLEY REGIONAL OFFICE
207453=KIM
#UPINGTON REGIONAL OFFICE
209953=UPT
#KURUMAN DISTRICT  OFFICE
210194=KUR
#PORT ELIZABETH REGIONAL OFFICE
210447=PEL
#EAST LONDON DISTRICT OFFICE
210785=ELD
#UMTATA REGIONAL OFFICE
210917=UMT
#QUEENSTOWN REGIONAL OFFICE
224661=QUE
#UITENHAGE DISTRICT OFFICE
225738=UTH
#GRAHAMSTOWN DISTRICT OFFICE
226596=GRA
#KING WILLIAMS TOWN REGIONAL OFFICE
226806=KWT
#KEMPTON PARK DISTRICT OFFICE
235460=KTP
#OR TAMBO DISTRICT OFFICE
252410=ORT
#ALBERTON DISTRICT OFFICE
270520=ALB
#VANDERBILJIPARK DISTRICT OFFICE
270687=VBP
#RANDFONTEIN REGIONAL OFFICE
270848=RFT
#CARLETONVILLE DISTRICT OFFICE
276224=CTV
#BETHLEHEM DISTRICT OFFICE
293757=BTM
#MASERU BRIDGE BORDER POST
293981=MSB
#BLOEMFONTEIN REGIONAL OFFICE
295138=BLF
#SASOLBURG DISTRICT OFFICE
296957=SLB
#BOTSHABELO DISTRICT OFFICE
297404=BTS
#KROONSTAD DISTRICT OFFICE
298052=KRS
#PHUTHADITJHABA REGIONAL OFFICE
304897=PTD
#WELKOM REGIONAL OFFICE
306266=WLK
#PHALABORWA REGIONAL OFFICE
350228=PLB
#POLOKWANE REGIONAL OFFICE
350523=PLK
#MOKOPANE REGIONAL OFFICE
351141=MKP
#BEIT BRIDGE BORDER POST
351871=BBR
#LEBOWAKGOMO DISTRICT OFFICE
352273=LBW
#GROBLERSDAL DISTRICT OFFICE
352671=GBR
#THOHOYANDOU REGIONAL OFFICE
375777=THD
#MAKHADO DISTRICT OFFICE
376394=MKH
#LEPHALALE DISTRICT OFFICE
381262=LPL
#TZANEEN REGIONAL OFFICE
381821=TZN
#RUSTENBURG REGIONAL OFFICE
404658=RST
#MANKWE DISTRICT OFFICE
405240=MKW
#VRYBURG DISTRICT OFFICE
407647=VRY
#BARBERTON DISTRICT OFFICE
407915=BBT
#NKOMAZI DISTRICT OFFICE
408243=NKM
#LYDENBURG DISTRICT OFFICE
414638=LYN
#MIDDLEBURG DISTRICT OFFICE
414770=MDB
#KLERKSDORP REGIONAL OFFICE
415291=KLK
#SECUNDA DISTRICT OFFICE
439374=SEC
#MAFIKENG REGIONAL OFFICE
466587=MFK
#MABOPANE DISTRICT OFFICE
466598=MBP
#LEHURUTSHE DISTRICT OFFICE
466611=LHR
#BRITS DISTRICT OFFICE
466699=BRT
#CENTURION DISTRICT OFFICE
681860=CNT
#VEREENIGING REGIONAL OFFICE
682095=VRN
#HEIDELBERG DISTRICT OFFICE
682290=HDL
#NIGEL DISTRICT OFFICE
682448=NGL
#BOKSBURG DISTRICT OFFICE
682619=BKS
#ROODEPOORT DISTRICT OFFICE
682741=RDP
#BENONI DISTRICT OFFICE
683064=BEN
#BRONKHORSTSPRUIT DISTRICT OFFICE
683229=BHS
#BRAKPAN DISTRICT OFFICE
683390=BRK
#SOWETO REGIONAL OFFICE
685768=SWT
#SPRINGS REGIONAL OFFICE
686397=SPR
#WALTLOO REVENUE MANAGEMENT 08 HEAD OFFICE
850053=WTL
#MUSINA DISTRICT OFFICE
853249=MUS
#SARS BAS TEST
5616687=SAR